flowchart LR
    N1["G0 - The System is..."]
    N2["G1 - System Definition"]
    N3["G2 - Quality Management"]
    N4["G3 - Safety Management"]
    N5["G4 - System Integration"]
    N6["G5 - Technical Assurance"]
    N7["G6 - Issues Management"]
    N8["G7 - Operational Readiness"]
    N9["G1.1 - Goal G1.1"]
    N10["G2.1 - Goal G2.1"]
    N11["G3.1 - Goal G3.1"]
    N12["G4.1 - Goal G4.1"]
    N13["G5.1 - Goal G5.1"]
    N14["G6.1 - Goal G6.1"]
    N15["G7.1 - Goal G7.1"]
    N1 -->|SupportedBy| N2
    N1 -->|SupportedBy| N3
    N1 -->|SupportedBy| N4
    N1 -->|SupportedBy| N5
    N1 -->|SupportedBy| N6
    N1 -->|SupportedBy| N7
    N1 -->|SupportedBy| N8
    N2 -->|SupportedBy| N9
    N3 -->|SupportedBy| N10
    N4 -->|SupportedBy| N11
    N5 -->|SupportedBy| N12
    N6 -->|SupportedBy| N13
    N7 -->|SupportedBy| N14
    N8 -->|SupportedBy| N15
